<?php

return [
    'users' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'username' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 50,
            ],
            'email' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 100,
            ],
            'password' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'full_name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'role' => [
                'type' => 'ENUM',
                'required' => true,
                'unique' => false,
                'options' => [
                    0 => 'super_admin',
                    1 => 'admin',
                    2 => 'editor',
                ],
                'default' => 'editor',
            ],
            'avatar' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'remember_token' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 100,
                'default' => null,
            ],
            'reset_token' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 100,
                'default' => null,
            ],
            'reset_expires' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'login_attempts' => [
                'type' => 'TINYINT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'locked_until' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'last_login' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'settings' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'setting_key' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 100,
            ],
            'setting_value' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'setting_group' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => 'general',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'pages' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 200,
            ],
            'content' => [
                'type' => 'LONGTEXT',
                'required' => false,
                'unique' => false,
            ],
            'featured_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'page_type' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'about',
                    1 => 'vision_mission',
                    2 => 'history',
                    3 => 'legality',
                    4 => 'custom',
                ],
                'default' => 'custom',
            ],
            'meta_title' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 200,
                'default' => null,
            ],
            'meta_description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'meta_keywords' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'draft',
                    1 => 'published',
                ],
                'default' => 'draft',
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_by' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'created_by' => [
                'table' => 'users',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
        ],
    ],
    'categories' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 100,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'news' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'category_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'excerpt' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'content' => [
                'type' => 'LONGTEXT',
                'required' => false,
                'unique' => false,
            ],
            'featured_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'meta_title' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 200,
                'default' => null,
            ],
            'meta_description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'meta_keywords' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'views' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'is_featured' => [
                'type' => 'TINYINT',
                'required' => false,
                'unique' => false,
                'length' => 1,
                'default' => '0',
            ],
            'allow_comments' => [
                'type' => 'TINYINT',
                'required' => false,
                'unique' => false,
                'length' => 1,
                'default' => '1',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'draft',
                    1 => 'published',
                ],
                'default' => 'draft',
            ],
            'published_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_by' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'category_id' => [
                'table' => 'categories',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
            'created_by' => [
                'table' => 'users',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
        ],
    ],
    'news_comments' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'news_id' => [
                'type' => 'INT',
                'required' => true,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'email' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'comment' => [
                'type' => 'TEXT',
                'required' => true,
                'unique' => false,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'pending',
                    1 => 'approved',
                    2 => 'rejected',
                ],
                'default' => 'pending',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'news_id' => [
                'table' => 'news',
                'column' => 'id',
                'delete' => 'CASCADE',
            ],
        ],
    ],
    'journals' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'authors' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'abstract' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'pdf_file' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'cover_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'download_count' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'published_year' => [
                'type' => 'YEAR',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'draft',
                    1 => 'published',
                ],
                'default' => 'draft',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'books' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'authors' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'isbn' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 20,
                'default' => null,
            ],
            'synopsis' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'cover_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'pdf_file' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'download_count' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'draft',
                    1 => 'published',
                ],
                'default' => 'draft',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'services' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 200,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'icon' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => 'bi-gear',
            ],
            'image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'activities' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'activity_date' => [
                'type' => 'DATE',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'research_fields' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 200,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'icon' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => 'bi-search',
            ],
            'image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'work_programs' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 200,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'year' => [
                'type' => 'YEAR',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'team' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'position' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'photo' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'education' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'profession' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 100,
                'default' => null,
            ],
            'biography' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'facebook' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'twitter' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'linkedin' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'instagram' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'organization_structure' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'parent_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'team_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'level' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '1',
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'parent_id' => [
                'table' => 'organization_structure',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
            'team_id' => [
                'table' => 'team',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
        ],
    ],
    'gallery' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 200,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'cover_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'album_type' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'photo',
                    1 => 'video',
                    2 => 'mixed',
                ],
                'default' => 'photo',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'gallery_images' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'gallery_id' => [
                'type' => 'INT',
                'required' => true,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 200,
                'default' => null,
            ],
            'image_path' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'youtube_url' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'media_type' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'image',
                    1 => 'video',
                ],
                'default' => 'image',
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'gallery_id' => [
                'table' => 'gallery',
                'column' => 'id',
                'delete' => 'CASCADE',
            ],
        ],
    ],
    'agenda' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'event_date' => [
                'type' => 'DATE',
                'required' => true,
                'unique' => false,
            ],
            'event_time' => [
                'type' => 'TIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'location' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'google_maps_embed' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'registration_url' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'featured_image' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'draft',
                    1 => 'published',
                ],
                'default' => 'draft',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'documents' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'file_path' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'file_size' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'category' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 100,
                'default' => null,
            ],
            'download_count' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'downloads' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => true,
                'length' => 255,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'file_path' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'file_type' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 20,
                'default' => null,
            ],
            'file_size' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'download_count' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'partners' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 150,
            ],
            'logo' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'website_url' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'testimonials' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'position' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 100,
                'default' => null,
            ],
            'organization' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 150,
                'default' => null,
            ],
            'photo' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'testimonial' => [
                'type' => 'TEXT',
                'required' => true,
                'unique' => false,
            ],
            'rating' => [
                'type' => 'TINYINT',
                'required' => false,
                'unique' => false,
                'default' => '5',
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'faq' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'question' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'answer' => [
                'type' => 'TEXT',
                'required' => true,
                'unique' => false,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'sliders' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'subtitle' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'image' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'button_text' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => null,
            ],
            'button_url' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'contact_messages' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'name' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'email' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'phone' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 20,
                'default' => null,
            ],
            'subject' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 200,
            ],
            'message' => [
                'type' => 'TEXT',
                'required' => true,
                'unique' => false,
            ],
            'ip_address' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 45,
                'default' => null,
            ],
            'is_read' => [
                'type' => 'TINYINT',
                'required' => false,
                'unique' => false,
                'length' => 1,
                'default' => '0',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'menus' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'title' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'url' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'parent_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'menu_location' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'header',
                    1 => 'footer',
                    2 => 'sidebar',
                ],
                'default' => 'header',
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'target' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => '_self',
                    1 => '_blank',
                ],
                'default' => '_self',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'deleted_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'parent_id' => [
                'table' => 'menus',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
        ],
    ],
    'social_media' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'platform' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 50,
            ],
            'url' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 255,
            ],
            'icon' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => null,
            ],
            'sort_order' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => '0',
            ],
            'status' => [
                'type' => 'ENUM',
                'required' => false,
                'unique' => false,
                'options' => [
                    0 => 'active',
                    1 => 'inactive',
                ],
                'default' => 'active',
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
            'updated_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'visitor_statistics' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'visit_date' => [
                'type' => 'DATE',
                'required' => true,
                'unique' => false,
            ],
            'page_url' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'ip_address' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 45,
                'default' => null,
            ],
            'user_agent' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'referrer' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
        ],
    ],
    'logs' => [
        'fields' => [
            'id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
            ],
            'user_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'action' => [
                'type' => 'VARCHAR',
                'required' => true,
                'unique' => false,
                'length' => 100,
            ],
            'module' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 50,
                'default' => null,
            ],
            'record_id' => [
                'type' => 'INT',
                'required' => false,
                'unique' => false,
                'default' => null,
            ],
            'description' => [
                'type' => 'TEXT',
                'required' => false,
                'unique' => false,
            ],
            'ip_address' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 45,
                'default' => null,
            ],
            'user_agent' => [
                'type' => 'VARCHAR',
                'required' => false,
                'unique' => false,
                'length' => 255,
                'default' => null,
            ],
            'created_at' => [
                'type' => 'DATETIME',
                'required' => false,
                'unique' => false,
                'default' => 'CURRENT_TIMESTAMP',
            ],
        ],
        'foreign' => [
            'user_id' => [
                'table' => 'users',
                'column' => 'id',
                'delete' => 'SET NULL',
            ],
        ],
    ],
];
